theme: jekyll-theme-cayman
title: 'UC Davis Bioinformatics Core 2018 RNA-Seq Workshop'
tagline: 'June 18th-22nd, 2018'
name: 'UC Davis Bioinformatics Core 2018 RNA-Seq Workshop'
github:
  repository_url: https://ucdavis-bioinformatics-training.github.io/2018-June-RNA-Seq-Workshop
